package com.gao.mapper;

import com.gao.pojo.Myuser;
import com.gao.pojo.MyuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Apr 02 08:47:27 CST 2018
     */
    long countByExample(MyuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Apr 02 08:47:27 CST 2018
     */
    int deleteByExample(MyuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Apr 02 08:47:27 CST 2018
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Apr 02 08:47:27 CST 2018
     */
    int insert(Myuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Apr 02 08:47:27 CST 2018
     */
    int insertSelective(Myuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Apr 02 08:47:27 CST 2018
     */
    List<Myuser> selectByExample(MyuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Apr 02 08:47:27 CST 2018
     */
    Myuser selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Apr 02 08:47:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") Myuser record, @Param("example") MyuserExample example);

    /** adf
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Apr 02 08:47:27 CST 2018
     */
    int updateByExample(@Param("record") Myuser record, @Param("example") MyuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Apr 02 08:47:27 CST 2018
     */
    int updateByPrimaryKeySelective(Myuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Apr 02 08:47:27 CST 2018
     */
    int updateByPrimaryKey(Myuser record);
}